package com.mocktalkback.global.common.dto;

import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ErrorCode {

    // ===== Common =====
    COMMON_BAD_REQUEST("COMMON_400", HttpStatus.BAD_REQUEST),
    COMMON_UNAUTHORIZED("COMMON_401", HttpStatus.UNAUTHORIZED),
    COMMON_FORBIDDEN("COMMON_403", HttpStatus.FORBIDDEN),
    COMMON_METHOD_NOT_ALLOWED("COMMON_405", HttpStatus.METHOD_NOT_ALLOWED),
    COMMON_CONFLICT("COMMON_409", HttpStatus.CONFLICT),
    COMMON_PAYLOAD_TOO_LARGE("COMMON_413", HttpStatus.CONTENT_TOO_LARGE),
    COMMON_INTERNAL_ERROR("COMMON_500", HttpStatus.INTERNAL_SERVER_ERROR),

    // ===== Auth / JWT =====
    AUTH_INVALID_CREDENTIALS("AUTH_001", HttpStatus.UNAUTHORIZED),
    AUTH_REFRESH_EXPIRED("AUTH_013", HttpStatus.UNAUTHORIZED),
    AUTH_REFRESH_INVALID("AUTH_014", HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_WITHDRAWN("AUTH_020", HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_DISABLED("AUTH_021", HttpStatus.UNAUTHORIZED),
    OAUTH2_CODE_INVALID("AUTH_030", HttpStatus.UNAUTHORIZED),

    // ===== User =====
    USER_NOT_FOUND("USER_404", HttpStatus.NOT_FOUND),
    USER_HANDLE_ALREADY_EXISTS("USER_020", HttpStatus.CONFLICT),
    USER_EMAIL_ALREADY_EXISTS("USER_021", HttpStatus.CONFLICT),
    USER_DELETE_CONFIRM_INVALID("USER_022", HttpStatus.BAD_REQUEST),
    USER_FIELD_REQUIRED("USER_023", HttpStatus.BAD_REQUEST),
    USER_FIELD_MAX_LENGTH("USER_024", HttpStatus.BAD_REQUEST),
    USER_PASSWORD_LENGTH("USER_025", HttpStatus.BAD_REQUEST),
    USER_PASSWORD_MISMATCH("USER_026", HttpStatus.BAD_REQUEST),
    USER_LOGIN_ID_REQUIRED("USER_027", HttpStatus.BAD_REQUEST),
    USER_LOGIN_ID_ALREADY_EXISTS("USER_028", HttpStatus.CONFLICT),

    // ===== Board =====
    BOARD_NOT_FOUND("BOARD_404", HttpStatus.NOT_FOUND),
    BOARD_ALREADY_SUBSCRIBED("BOARD_010", HttpStatus.CONFLICT),
    BOARD_MEMBER_ALREADY_JOINED("BOARD_011", HttpStatus.CONFLICT),
    BOARD_MEMBER_NOT_FOUND("BOARD_012", HttpStatus.NOT_FOUND),

    // ===== Article =====
    ARTICLE_NOT_FOUND("ARTICLE_404", HttpStatus.NOT_FOUND),
    ATTACHMENT_NOT_FOUND("ARTICLE_405", HttpStatus.NOT_FOUND),
    ARTICLE_REACTION_NOT_FOUND("ARTICLE_421", HttpStatus.NOT_FOUND),
    ARTICLE_BOOKMARK_NOT_FOUND("ARTICLE_422", HttpStatus.NOT_FOUND),
    ARTICLE_FILE_LINK_NOT_FOUND("ARTICLE_423", HttpStatus.NOT_FOUND),
    ARTICLE_IMPORT_ASSET_FILE_MISSING("ARTICLE_424", HttpStatus.BAD_REQUEST),

    // ===== Comment =====
    COMMENT_NOT_FOUND("COMMENT_404", HttpStatus.NOT_FOUND),

    // ===== Notification =====
    NOTIFICATION_NOT_FOUND("NOTIFICATION_404", HttpStatus.NOT_FOUND),
    NOTIFICATION_SSE_TICKET_INVALID("NOTIFICATION_010", HttpStatus.UNAUTHORIZED),

    // ===== File =====
    FILE_NOT_FOUND("FILE_404", HttpStatus.NOT_FOUND),
    FILE_VARIANT_UNSUPPORTED("FILE_010", HttpStatus.BAD_REQUEST),
    FILE_CLASS_NOT_FOUND("FILE_021", HttpStatus.NOT_FOUND),

    // ===== Moderation =====
    MEMBER_NOT_FOUND("MOD_404", HttpStatus.NOT_FOUND),
    REPORT_NOT_FOUND("MOD_405", HttpStatus.NOT_FOUND),
    SANCTION_NOT_FOUND("MOD_406", HttpStatus.NOT_FOUND),
    SANCTION_ALREADY_REVOKED("MOD_420", HttpStatus.CONFLICT),
    BOARD_REPORT_NOT_FOUND("MOD_407", HttpStatus.NOT_FOUND),
    BOARD_SANCTION_NOT_FOUND("MOD_408", HttpStatus.NOT_FOUND),
    BOARD_CATEGORY_NOT_FOUND("MOD_409", HttpStatus.NOT_FOUND),
    BOARD_CATEGORY_INVALID("MOD_410", HttpStatus.BAD_REQUEST),
    BOARD_CONTENT_INVALID("MOD_411", HttpStatus.BAD_REQUEST),
    MEMBER_PENDING_APPROVAL_ONLY("MOD_412", HttpStatus.CONFLICT),
    MEMBER_ROLE_INVALID("MOD_413", HttpStatus.BAD_REQUEST),
    MEMBER_ROLE_CHANGE_INVALID("MOD_414", HttpStatus.BAD_REQUEST),
    MEMBER_STATUS_CHANGE_INVALID("MOD_415", HttpStatus.BAD_REQUEST),
    MEMBER_NOT_BOARD_MEMBER("MOD_416", HttpStatus.BAD_REQUEST),
    MEMBER_BLOCK_PENDING_INVALID("MOD_417", HttpStatus.BAD_REQUEST),
    MEMBER_UNBLOCK_INVALID("MOD_418", HttpStatus.BAD_REQUEST),

    // ===== Reaction =====
    REACTION_TYPE_REQUIRED("REACT_001", HttpStatus.BAD_REQUEST),
    REACTION_TYPE_INVALID("REACT_002", HttpStatus.BAD_REQUEST),

    // ===== Article (extended) =====
    ARTICLE_CATEGORY_FILTER_CONFLICT("ARTICLE_406", HttpStatus.BAD_REQUEST),
    ARTICLE_FILE_NOT_ATTACHABLE("ARTICLE_407", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_ZIP_PATH_INVALID("ARTICLE_408", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_VALIDATION_FAILED("ARTICLE_409", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_ZIP_EMPTY("ARTICLE_410", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_MANIFEST_ARTICLES("ARTICLE_411", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_NO_MARKDOWN("ARTICLE_412", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_ZIP_READ_FAILED("ARTICLE_413", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_MANIFEST_SINGLE("ARTICLE_414", HttpStatus.BAD_REQUEST),
    ARTICLE_CONTENT_FORMAT_REQUIRED("ARTICLE_415", HttpStatus.BAD_REQUEST),
    ARTICLE_CONTENT_SOURCE_REQUIRED("ARTICLE_416", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_OWNER_EMPTY("ARTICLE_417", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_ASSETS_EMPTY("ARTICLE_418", HttpStatus.BAD_REQUEST),
    ARTICLE_IMPORT_ASSETS_MIME_EMPTY("ARTICLE_419", HttpStatus.BAD_REQUEST),
    ARTICLE_ID_EMPTY("ARTICLE_420", HttpStatus.BAD_REQUEST),

    // ===== Board (extended) =====
    BOARD_INSUFFICIENT_POINTS("BOARD_013", HttpStatus.CONFLICT),
    BOARD_SUBSCRIBE_NOT_FOUND("BOARD_014", HttpStatus.NOT_FOUND),
    BOARD_FILE_NOT_FOUND("BOARD_015", HttpStatus.NOT_FOUND),

    // ===== Comment (extended) =====
    COMMENT_WRONG_ARTICLE("COMMENT_010", HttpStatus.BAD_REQUEST),
    COMMENT_DELETED_NO_REACTION("COMMENT_011", HttpStatus.BAD_REQUEST),
    COMMENT_DELETED_NO_EDIT("COMMENT_012", HttpStatus.BAD_REQUEST),
    COMMENT_CONTENT_REQUIRED("COMMENT_013", HttpStatus.BAD_REQUEST),
    COMMENT_FILE_NOT_FOUND("COMMENT_014", HttpStatus.NOT_FOUND),
    COMMENT_REACTION_NOT_FOUND("COMMENT_015", HttpStatus.NOT_FOUND),

    // ===== Moderation (extended) =====
    REPORT_SELF("MOD_419", HttpStatus.BAD_REQUEST),
    REPORT_ALREADY_IN_PROGRESS("MOD_429", HttpStatus.CONFLICT),
    REPORT_DUPLICATE_24H("MOD_421", HttpStatus.CONFLICT),
    SANCTION_END_BEFORE_START("MOD_422", HttpStatus.BAD_REQUEST),
    SANCTION_BOARD_ID_REQUIRED("MOD_423", HttpStatus.BAD_REQUEST),
    REPORT_TYPE_UNSUPPORTED("MOD_424", HttpStatus.BAD_REQUEST),
    BOARD_CATEGORY_DUPLICATE("MOD_425", HttpStatus.CONFLICT),
    BOARD_CATEGORY_HAS_ARTICLES("MOD_426", HttpStatus.CONFLICT),
    BOARD_CATEGORY_NAME_REQUIRED("MOD_427", HttpStatus.BAD_REQUEST),
    ROLE_NOT_FOUND("MOD_428", HttpStatus.NOT_FOUND),

    // ===== Search / Notification =====
    SEARCH_KEYWORD_REQUIRED("SEARCH_001", HttpStatus.BAD_REQUEST),
    NOTIFICATION_REDIRECT_REQUIRED("NOTIF_010", HttpStatus.BAD_REQUEST),
    NOTIFICATION_SSE_TICKET_EMPTY("NOTIF_011", HttpStatus.BAD_REQUEST),

    // ===== Upload =====
    UPLOAD_PURPOSE_EMPTY("UPLOAD_001", HttpStatus.BAD_REQUEST),
    UPLOAD_FILENAME_EMPTY("UPLOAD_002", HttpStatus.BAD_REQUEST),
    UPLOAD_CONTENT_TYPE_EMPTY("UPLOAD_003", HttpStatus.BAD_REQUEST),
    UPLOAD_FILE_SIZE_INVALID("UPLOAD_004", HttpStatus.BAD_REQUEST),
    UPLOAD_FILE_SIZE_MAX("UPLOAD_005", HttpStatus.BAD_REQUEST),
    UPLOAD_BOARD_CONTEXT_EMPTY("UPLOAD_006", HttpStatus.BAD_REQUEST),
    UPLOAD_BOARD_ID_INVALID("UPLOAD_007", HttpStatus.BAD_REQUEST),
    UPLOAD_BOARD_CHANNEL_EMPTY("UPLOAD_008", HttpStatus.BAD_REQUEST),
    UPLOAD_FILE_TYPE_NOT_ALLOWED("UPLOAD_009", HttpStatus.BAD_REQUEST),
    UPLOAD_EXTENSION_BLOCKED("UPLOAD_010", HttpStatus.BAD_REQUEST),
    UPLOAD_FILE_TYPE_BLOCKED("UPLOAD_011", HttpStatus.BAD_REQUEST),
    UPLOAD_IMAGE_ONLY("UPLOAD_012", HttpStatus.BAD_REQUEST),
    UPLOAD_VIDEO_FORMAT_INVALID("UPLOAD_013", HttpStatus.BAD_REQUEST),
    UPLOAD_SESSION_STATE_EMPTY("UPLOAD_014", HttpStatus.BAD_REQUEST),
    UPLOAD_TOKEN_EMPTY("UPLOAD_015", HttpStatus.BAD_REQUEST),
    UPLOAD_TOKEN_INVALID("UPLOAD_019", HttpStatus.BAD_REQUEST),
    UPLOAD_FILE_INFO_MISSING("UPLOAD_016", HttpStatus.BAD_REQUEST),
    UPLOAD_SIZE_MISMATCH("UPLOAD_017", HttpStatus.BAD_REQUEST),
    UPLOAD_TOKEN_OWNER_MISMATCH("UPLOAD_018", HttpStatus.BAD_REQUEST),

    // ===== File (extended) =====
    FILE_CLASS_CODE_EMPTY("FILE_011", HttpStatus.BAD_REQUEST),
    FILE_OWNER_EMPTY("FILE_012", HttpStatus.BAD_REQUEST),
    FILE_BYTES_EMPTY("FILE_013", HttpStatus.BAD_REQUEST),
    STORAGE_KEY_EMPTY("FILE_014", HttpStatus.BAD_REQUEST),
    STORAGE_KEY_PATH_EMPTY("FILE_015", HttpStatus.BAD_REQUEST),
    FILE_SAVED_INFO_EMPTY("FILE_016", HttpStatus.BAD_REQUEST),
    FILE_ORIGINAL_PATH_EMPTY("FILE_017", HttpStatus.BAD_REQUEST),
    DELETE_RETRY_EMPTY("FILE_018", HttpStatus.BAD_REQUEST),
    EDITOR_FILE_UNSUPPORTED("FILE_019", HttpStatus.BAD_REQUEST),
    EDITOR_MEDIA_TYPE_INVALID("FILE_020", HttpStatus.BAD_REQUEST),

    // ===== Market =====
    MARKET_IMPORT_READ_FAILED("MARKET_001", HttpStatus.BAD_REQUEST),
    MARKET_IMPORT_FORMAT_UNSUPPORTED("MARKET_002", HttpStatus.BAD_REQUEST),
    MARKET_IMPORT_CSV_EMPTY("MARKET_003", HttpStatus.BAD_REQUEST),
    MARKET_IMPORT_XLSX_EMPTY("MARKET_004", HttpStatus.BAD_REQUEST),
    MARKET_IMPORT_XLSX_PARSE_FAILED("MARKET_005", HttpStatus.BAD_REQUEST),
    MARKET_INSTRUMENT_CODE_REQUIRED("MARKET_006", HttpStatus.BAD_REQUEST),
    MARKET_OBSERVED_AT_REQUIRED("MARKET_007", HttpStatus.BAD_REQUEST),
    MARKET_PRICE_VALUE_REQUIRED("MARKET_008", HttpStatus.BAD_REQUEST),
    MARKET_INSTRUMENT_MISMATCH("MARKET_009", HttpStatus.BAD_REQUEST),
    MARKET_INSTRUMENT_UNKNOWN("MARKET_010", HttpStatus.BAD_REQUEST),
    MARKET_INSTRUMENT_CODE_EMPTY("MARKET_011", HttpStatus.BAD_REQUEST),
    MARKET_INSTRUMENT_UNSUPPORTED("MARKET_012", HttpStatus.BAD_REQUEST),
    MARKET_OBSERVED_AT_EMPTY("MARKET_013", HttpStatus.BAD_REQUEST),
    MARKET_OBSERVED_AT_INVALID("MARKET_014", HttpStatus.BAD_REQUEST),
    MARKET_PRICE_EMPTY("MARKET_015", HttpStatus.BAD_REQUEST),
    MARKET_PRICE_INVALID("MARKET_016", HttpStatus.BAD_REQUEST),
    MARKET_PERIOD_RANGE_INVALID("MARKET_017", HttpStatus.BAD_REQUEST),
    MARKET_PERIOD_START_AFTER_END("MARKET_018", HttpStatus.BAD_REQUEST),
    MARKET_PERIOD_CUSTOM_INVALID("MARKET_019", HttpStatus.BAD_REQUEST),
    MARKET_SYMBOL_EMPTY("MARKET_020", HttpStatus.BAD_REQUEST),
    MARKET_PERIOD_CODE_EMPTY("MARKET_021", HttpStatus.BAD_REQUEST),

    // ===== Pagination =====
    PAGE_INVALID("PAGE_001", HttpStatus.BAD_REQUEST),
    PAGE_SIZE_INVALID("PAGE_002", HttpStatus.BAD_REQUEST),

    // ===== Newsbot =====
    NEWSBOT_JOB_NOT_FOUND("NEWSBOT_404", HttpStatus.NOT_FOUND),
    NEWSBOT_SOURCE_SAVE_FAILED("NEWSBOT_410", HttpStatus.BAD_REQUEST),
    NEWSBOT_SOURCE_READ_FAILED("NEWSBOT_411", HttpStatus.BAD_REQUEST),
    NEWSBOT_SOURCE_UNSUPPORTED("NEWSBOT_412", HttpStatus.BAD_REQUEST),
    NEWSBOT_JOB_NAME_DUPLICATE("NEWSBOT_413", HttpStatus.CONFLICT),
    NEWSBOT_TARGET_BOARD_NAME_REQUIRED("NEWSBOT_414", HttpStatus.BAD_REQUEST),
    NEWSBOT_TARGET_BOARD_MISSING("NEWSBOT_415", HttpStatus.BAD_REQUEST),
    NEWSBOT_TARGET_CATEGORY_MISSING("NEWSBOT_416", HttpStatus.BAD_REQUEST),
    NEWSBOT_JOB_ALREADY_RUNNING("NEWSBOT_409", HttpStatus.CONFLICT);

    private final String code;
    private final HttpStatus httpStatus;

    ErrorCode(String code, HttpStatus httpStatus) {
        this.code = code;
        this.httpStatus = httpStatus;
    }

    public String getMessageKey() {
        return "error." + name();
    }
}